ci, gha: Build Android artifacts

diff --git a/.github/workflows/artifacts.yml b/.github/workflows/artifacts.yml
--- a/.github/workflows/artifacts.yml
+++ b/.github/workflows/artifacts.yml
@@ -18,39 +18,44 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  cross-build:
-    name: ${{ matrix.host.name }}
+  android:
+    name: Android
+    # name: ${{ matrix.host.name }}
     runs-on: ubuntu-latest
+    container: ubuntu:22.04
 
-    strategy:
-      fail-fast: false
-      matrix:
-        host:
-          - name: 'macOS arm64'
-            packages: ''
-            triplet: 'arm64-apple-darwin'
-            compiler: 'clang'
-            configure_options: ''
-            gui_exe: 'bitcoin-qt'
-            artifact: 'unsecure_macos_apple_silicon_gui'
-          - name: 'macOS x86_64'
-            packages: ''
-            triplet: 'x86_64-apple-darwin'
-            compiler: 'clang'
-            configure_options: ''
-            gui_exe: 'bitcoin-qt'
-            artifact: 'unsecure_macos_intel_gui'
-          - name: 'Windows'
-            packages: 'g++-mingw-w64-x86-64-posix'
-            triplet: 'x86_64-w64-mingw32'
-            compiler: 'x86_64-w64-mingw32-g++-posix'
-            configure_options: 'CXXFLAGS=-Wno-return-type'
-            gui_exe: 'bitcoin-qt.exe'
-            artifact: 'unsecure_windows_gui'
+    # strategy:
+    #   fail-fast: false
+    #   matrix:
+    #     host:
+    #       - name: 'macOS arm64'
+    #         packages: ''
+    #         triplet: 'arm64-apple-darwin'
+    #         compiler: 'clang'
+    #         configure_options: ''
+    #         gui_exe: 'bitcoin-qt'
+    #         artifact: 'unsecure_macos_apple_silicon_gui'
+    #       - name: 'macOS x86_64'
+    #         packages: ''
+    #         triplet: 'x86_64-apple-darwin'
+    #         compiler: 'clang'
+    #         configure_options: ''
+    #         gui_exe: 'bitcoin-qt'
+    #         artifact: 'unsecure_macos_intel_gui'
+    #       - name: 'Windows'
+    #         packages: 'g++-mingw-w64-x86-64-posix'
+    #         triplet: 'x86_64-w64-mingw32'
+    #         compiler: 'x86_64-w64-mingw32-g++-posix'
+    #         configure_options: 'CXXFLAGS=-Wno-return-type'
+    #         gui_exe: 'bitcoin-qt.exe'
+    #         artifact: 'unsecure_windows_gui'
 
     env:
-      XCODE_VERSION: '12.2'
-      XCODE_BUILD_ID: '12B45b'
+      ANDROID_HOME: '/tmp/Android'
+      ANDROID_API_LEVEL: '28'
+      ANDROID_BUILD_TOOLS_VERSION: '28.0.3'
+      ANDROID_NDK_VERSION: '23.2.8568313'
+      ANDROID_TOOLS_URL: 'https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip'
       CCACHE_MAXSIZE: '30M'
 
     steps:
@@ -59,15 +64,28 @@ jobs:
 
       - name: Install dependency packages
         run: |
-          sudo apt-get update
-          sudo apt-get install ccache ${{ matrix.host.packages }}
-          echo "CCACHE_DIR=${{ runner.temp }}/ccache" >> "$GITHUB_ENV"
+          apt-get update
+          apt-get install --no-install-recommends -y ca-certificates curl g++ lbzip2 libtool make openjdk-8-jdk patch pkg-config python3 unzip xz-utils
+
+      - name: Install Android tools
+        run: |
+          curl --location --fail ${{ env.ANDROID_TOOLS_URL }} -o android-tools.zip
+          mkdir -p ${{ env.ANDROID_HOME }}
+          unzip -o android-tools.zip -d ${{ env.ANDROID_HOME }}
+          yes | ${{ env.ANDROID_HOME }}/cmdline-tools/bin/sdkmanager --sdk_root=${{ env.ANDROID_HOME }} --install "build-tools;${{ env.ANDROID_BUILD_TOOLS_VERSION }}" "platform-tools" "platforms;android-31" "platforms;android-${{ env.ANDROID_API_LEVEL }}" "ndk;${{ env.ANDROID_NDK_VERSION }}"
+
+      # - name: Install dependency packages
+      #   run: |
+      #     sudo apt-get update
+      #     sudo apt-get install ccache
+      #     echo "CCACHE_DIR=${{ runner.temp }}/ccache" >> "$GITHUB_ENV"
+      #   # sudo apt-get install ccache ${{ matrix.host.packages }}
+      #   # echo "CCACHE_DIR=${{ runner.temp }}/ccache" >> "$GITHUB_ENV"
 
       - name: Depends fingerprint
         id: depends_fingerprint
         run: |
-          if ${{ !endsWith(matrix.host.triplet, '-apple-darwin') }}; then ${{ matrix.host.compiler }} -v 2>&1 | tee depends/compiler-version; fi
-          if ${{ endsWith(matrix.host.triplet, '-apple-darwin') }}; then echo ${{ env.XCODE_VERSION }} ${{ env.XCODE_BUILD_ID }} > depends/sdk-version; fi
+          echo ${{ env.ANDROID_NDK_VERSION }} > depends/android-ndk-version
           echo "hash=${{ hashFiles('./depends/**') }}" >> "$GITHUB_OUTPUT"
 
       - name: Depends cache
@@ -76,49 +94,41 @@ jobs:
         with:
           path: |
             depends/built
-            depends/SDKs
-          key: ${{ matrix.host.triplet }}-depends-${{ steps.depends_fingerprint.outputs.hash }}
-
-      - name: Fetch SDK
-        if: endsWith(matrix.host.triplet, '-apple-darwin') && steps.depends_cache.outputs.cache-hit != 'true'
-        run: |
-          curl --location --fail https://bitcoincore.org/depends-sources/sdks/Xcode-${{ env.XCODE_VERSION }}-${{ env.XCODE_BUILD_ID }}-extracted-SDK-with-libcxx-headers.tar.gz -o sdk.tar.gz
-          mkdir depends/SDKs
-          tar -C depends/SDKs -xf sdk.tar.gz
+          # key: ${{ matrix.host.triplet }}-depends-${{ steps.depends_fingerprint.outputs.hash }}
+          key: android-depends-${{ steps.depends_fingerprint.outputs.hash }}
 
       - name: Build depends
         run: |
-          patch -p1 -i ci/hosts_darwin_mk.patch
           cd depends
-          make -j$(nproc) HOST=${{ matrix.host.triplet }} LOG=1
+          make -j$(nproc) HOST=aarch64-linux-android ANDROID_SDK=${{ env.ANDROID_HOME }} ANDROID_NDK=${{ env.ANDROID_HOME }}/ndk/${{ env.ANDROID_NDK_VERSION }} ANDROID_API_LEVEL=${{ env.ANDROID_API_LEVEL }} ANDROID_TOOLCHAIN_BIN=${{ env.ANDROID_HOME }}/ndk/${{ env.ANDROID_NDK_VERSION }}/toolchains/llvm/prebuilt/linux-x86_64/bin
 
-      - name: Restore Ccache cache
-        uses: actions/cache/restore@v3
-        id: ccache-cache
-        with:
-          path: ${{ env.CCACHE_DIR }}
-          key: ${{ matrix.host.triplet }}-ccache-${{ github.run_id }}
-          restore-keys: ${{ matrix.host.triplet }}-ccache-
+      # # - name: Restore Ccache cache
+      # #   uses: actions/cache/restore@v3
+      # #   id: ccache-cache
+      # #   with:
+      # #     path: ${{ env.CCACHE_DIR }}
+      # #     key: ${{ matrix.host.triplet }}-ccache-${{ github.run_id }}
+      # #     restore-keys: ${{ matrix.host.triplet }}-ccache-
 
-      - name: Configure
-        run: |
-          ./autogen.sh
-          ./configure CONFIG_SITE=${{ github.workspace }}/depends/${{ matrix.host.triplet }}/share/config.site --disable-dependency-tracking --enable-werror ${{ matrix.host.configure_options }} || (cat config.log; false)
+      # # - name: Configure
+      # #   run: |
+      # #     ./autogen.sh
+      # #     ./configure CONFIG_SITE=${{ github.workspace }}/depends/${{ matrix.host.triplet }}/share/config.site --disable-dependency-tracking --enable-werror ${{ matrix.host.configure_options }} || (cat config.log; false)
 
-      - name: Build GUI
-        run: |
-          ccache --zero-stats
-          make -j$(nproc) src/qt/${{ matrix.host.gui_exe }}
-          ccache --version | head -n 1 && ccache --show-stats
+      # # - name: Build GUI
+      # #   run: |
+      # #     ccache --zero-stats
+      # #     make -j$(nproc) src/qt/${{ matrix.host.gui_exe }}
+      # #     ccache --version | head -n 1 && ccache --show-stats
 
-      - name: Save Ccache cache
-        uses: actions/cache/save@v3
-        if: github.event_name != 'pull_request' && steps.ccache-cache.outputs.cache-hit != 'true'
-        with:
-          path: ${{ env.CCACHE_DIR }}
-          key: ${{ matrix.host.triplet }}-ccache-${{ github.run_id }}
+      # # - name: Save Ccache cache
+      # #   uses: actions/cache/save@v3
+      # #   if: github.event_name != 'pull_request' && steps.ccache-cache.outputs.cache-hit != 'true'
+      # #   with:
+      # #     path: ${{ env.CCACHE_DIR }}
+      # #     key: ${{ matrix.host.triplet }}-ccache-${{ github.run_id }}
 
-      - uses: actions/upload-artifact@v3
-        with:
-          name: ${{ matrix.host.artifact }}
-          path: src/qt/${{ matrix.host.gui_exe }}
+      # # - uses: actions/upload-artifact@v3
+      # #   with:
+      # #     name: ${{ matrix.host.artifact }}
+      # #     path: src/qt/${{ matrix.host.gui_exe }}
